spring.datasource.url=jdbc:postgresql://localhost:5433/ordersdb
spring.datasource.username=postgres
spring.datasource.password=smile1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

server.port=8080

logging.level.com.orders=DEBUG
